ALTER TABLE PUBLIC.SYMBOL ADD COLUMN CurrencyTmp VARCHAR(255);

UPDATE SYMBOL SET CurrencyTmp='AUD' WHERE Currency='0';
UPDATE SYMBOL SET CurrencyTmp='CAD' WHERE Currency='1';
UPDATE SYMBOL SET CurrencyTmp='CHF' WHERE Currency='2';
UPDATE SYMBOL SET CurrencyTmp='CZK' WHERE Currency='3';
UPDATE SYMBOL SET CurrencyTmp='EUR' WHERE Currency='4';
UPDATE SYMBOL SET CurrencyTmp='GBP' WHERE Currency='5';
UPDATE SYMBOL SET CurrencyTmp='JPY' WHERE Currency='6';
UPDATE SYMBOL SET CurrencyTmp='NZD' WHERE Currency='7';
UPDATE SYMBOL SET CurrencyTmp='RUB' WHERE Currency='8';
UPDATE SYMBOL SET CurrencyTmp='SEK' WHERE Currency='9';
UPDATE SYMBOL SET CurrencyTmp='USD' WHERE Currency='10';

ALTER TABLE PUBLIC.SYMBOL DROP COLUMN CURRENCY;
ALTER TABLE PUBLIC.SYMBOL ALTER COLUMN CurrencyTmp RENAME TO CURRENCY;