INSERT INTO SYMBOL VALUES(-1,'0','','Error','UNKNOWN','ERROR');
UPDATE PUBLIC.TRANSACTION SET SYMBOL_ID=-1 WHERE SYMBOL_ID NOT IN(SELECT ID FROM PUBLIC.SYMBOL);
UPDATE PUBLIC.LABEL SET LABEL='ERROR' WHERE LABEL = '';
UPDATE PUBLIC.TRANSACTION SET TYPE='ERROR' WHERE TYPE IS NULL;
UPDATE PUBLIC.SYMBOL SET SECTOR='UNKNOWN' WHERE SECTOR IS NULL;
UPDATE PUBLIC.SYMBOL SET CURRENCY='ERROR' WHERE CURRENCY IS NULL;