INSERT INTO SYMBOL VALUES(-1,'0','','Error','UNKNOWN','ERR');
UPDATE PUBLIC.TRANSACTION SET SYMBOL_ID=-1 WHERE SYMBOL_ID NOT IN(SELECT ID FROM PUBLIC.SYMBOL);
UPDATE PUBLIC.LABEL SET LABEL='ERROR' WHERE LABEL = '';
UPDATE PUBLIC.TRANSACTION SET TYPE='ERROR' WHERE TYPE IS NULL;
UPDATE PUBLIC.SYMBOL SET SECTOR='UNKNOWN' WHERE SECTOR IS NULL;
UPDATE PUBLIC.SYMBOL SET CURRENCY='ERR' WHERE CURRENCY IS NULL;
UPDATE PUBLIC.TRANSACTION SET PRICE=0.00000001 WHERE PRICE = 0;
UPDATE PUBLIC.TRANSACTION SET QUANTITY=0.00000001 WHERE QUANTITY = 0;