ALTER TABLE PUBLIC.HISTORICALPRICE ADD CONSTRAINT PK_HISTORICALPRICE_ID PRIMARY KEY (ID);

ALTER TABLE PUBLIC.HISTORICALPRICE ALTER COLUMN ID SET NOT NULL;
ALTER TABLE PUBLIC.HISTORICALPRICE ALTER COLUMN CUSTOMPRICE SET NOT NULL;
ALTER TABLE PUBLIC.HISTORICALPRICE ALTER COLUMN PRICE SET NOT NULL;
ALTER TABLE PUBLIC.HISTORICALPRICE ALTER COLUMN YEAR SET NOT NULL;
	
ALTER TABLE PUBLIC.LABEL ADD CONSTRAINT PK_LABEL_ID PRIMARY KEY (ID)
ALTER TABLE PUBLIC.LABEL ALTER COLUMN ID SET NOT NULL;
ALTER TABLE PUBLIC.LABEL ALTER COLUMN LABEL SET NOT NULL;
ALTER TABLE PUBLIC.LABEL ADD CONSTRAINT UN_LABEL_NAME UNIQUE (LABEL);

ALTER TABLE PUBLIC.SYMBOL_PRICES ADD CONSTRAINT PK_SYMBOLPRICES_IDS PRIMARY KEY (SYMBOLID, PRICEID)
ALTER TABLE PUBLIC.SYMBOL_PRICES ALTER COLUMN SYMBOLID SET NOT NULL;
ALTER TABLE PUBLIC.SYMBOL_PRICES ALTER COLUMN PRICEID SET NOT NULL;
ALTER TABLE PUBLIC.SYMBOL_PRICES ADD CONSTRAINT UN_SYMBOLPRICES_PRICEID UNIQUE (PRICEID);
ALTER TABLE PUBLIC.SYMBOL_PRICES ADD CONSTRAINT FK_SYMBOL_HISTORICALPRICE FOREIGN KEY(PRICEID) REFERENCES PUBLIC.HISTORICALPRICE(ID)

ALTER TABLE PUBLIC.SYMBOL ADD CONSTRAINT PK_SYMBOL_ID PRIMARY KEY (ID)
ALTER TABLE PUBLIC.SYMBOL ALTER COLUMN ID SET NOT NULL;
ALTER TABLE PUBLIC.SYMBOL ALTER COLUMN ISCUSTOMPRICEFIRST SET NOT NULL;
ALTER TABLE PUBLIC.SYMBOL ALTER COLUMN TICKER SET NOT NULL;
ALTER TABLE PUBLIC.SYMBOL ALTER COLUMN CURRENCY SET NOT NULL;
ALTER TABLE PUBLIC.SYMBOL ADD CONSTRAINT UN_SYMBOL_TICKER UNIQUE (TICKER);
ALTER TABLE PUBLIC.SYMBOL ALTER COLUMN SECTOR SET NOT NULL;

ALTER TABLE PUBLIC.TRANSACTION_LABEL ADD CONSTRAINT PK_TRANSACTIONLABEL_IDS PRIMARY KEY (TRANSACTIONID, LABELID)
ALTER TABLE PUBLIC.TRANSACTION_LABEL ADD CONSTRAINT FK_TRANSACTION_LABEL FOREIGN KEY(LABELID) REFERENCES PUBLIC.LABEL(ID)
ALTER TABLE PUBLIC.TRANSACTION_LABEL ALTER COLUMN TRANSACTIONID SET NOT NULL;
ALTER TABLE PUBLIC.TRANSACTION_LABEL ALTER COLUMN LABELID SET NOT NULL;

ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT PK_TRANSACTION_ID PRIMARY KEY (ID)
ALTER TABLE PUBLIC.TRANSACTION ALTER COLUMN ID SET NOT NULL;
ALTER TABLE PUBLIC.TRANSACTION ALTER COLUMN COMMISSION SET NOT NULL;
ALTER TABLE PUBLIC.TRANSACTION ALTER COLUMN PRICE SET NOT NULL;
ALTER TABLE PUBLIC.TRANSACTION ALTER COLUMN QUANTITY SET NOT NULL;
ALTER TABLE PUBLIC.TRANSACTION ALTER COLUMN DATE SET NOT NULL;
ALTER TABLE PUBLIC.TRANSACTION ALTER COLUMN SYMBOL_ID SET NOT NULL;

UPDATE PUBLIC.TRANSACTION SET TYPE='BUY' WHERE TYPE IS NULL;
ALTER TABLE PUBLIC.TRANSACTION ALTER COLUMN TYPE SET NOT NULL;

ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT FK_TRANSACTION_SYMBOL FOREIGN KEY(SYMBOL_ID) REFERENCES PUBLIC.SYMBOL(ID)	

ALTER TABLE PUBLIC.VERSION ADD CONSTRAINT PK_VERSION_ID PRIMARY KEY (ID)
ALTER TABLE PUBLIC.VERSION ALTER COLUMN ID SET NOT NULL;
ALTER TABLE PUBLIC.VERSION ALTER COLUMN DATABASEVERSION SET NOT NULL;
ALTER TABLE PUBLIC.VERSION ADD CONSTRAINT CK_VERSION_DATABASEVERSION CHECK (DATABASEVERSION > 1);
ALTER TABLE PUBLIC.VERSION ADD CONSTRAINT UN_VERSION_DATABASEVERSION UNIQUE (DATABASEVERSION);
