ALTER TABLE PUBLIC.HISTORICALPRICE ADD CONSTRAINT PK_HISTORICALPRICE_ID PRIMARY KEY (ID);
ALTER TABLE public.HISTORICALPRICE ADD CONSTRAINT NN_HISTORICALPRICE_ID CHECK (ID IS NOT NULL);
ALTER TABLE public.HISTORICALPRICE ADD CONSTRAINT NN_HISTORICALPRICE_CUSTOMPRICE CHECK (CUSTOMPRICE IS NOT NULL);
ALTER TABLE public.HISTORICALPRICE ADD CONSTRAINT NN_HISTORICALPRICE_PRICE CHECK (PRICE IS NOT NULL);
ALTER TABLE public.HISTORICALPRICE ADD CONSTRAINT NN_HISTORICALPRICE_YEAR CHECK (YEAR IS NOT NULL);
-- ALTER TABLE public.HISTORICALPRICE ADD CONSTRAINT UN_HISTORICALPRICE_YEAR UNIQUE (YEAR);
	
ALTER TABLE PUBLIC.LABEL ADD CONSTRAINT PK_LABEL_ID PRIMARY KEY (ID)
ALTER TABLE PUBLIC.LABEL ADD CONSTRAINT NN_LABEL_ID CHECK (ID IS NOT NULL);
ALTER TABLE PUBLIC.LABEL ADD CONSTRAINT NN_LABEL_NAME CHECK (LABEL IS NOT NULL);
ALTER TABLE PUBLIC.LABEL ADD CONSTRAINT UN_LABEL_NAME UNIQUE (LABEL);

ALTER TABLE PUBLIC.SYMBOL_PRICES ADD CONSTRAINT PK_SYMBOLPRICES_IDS PRIMARY KEY (SYMBOLID, PRICEID)
ALTER TABLE PUBLIC.SYMBOL_PRICES ADD CONSTRAINT NN_SYMBOLPRICES_SYMBOLID CHECK (SYMBOLID IS NOT NULL);
ALTER TABLE PUBLIC.SYMBOL_PRICES ADD CONSTRAINT NN_SYMBOLPRICES_PRICEID CHECK (PRICEID IS NOT NULL);
ALTER TABLE PUBLIC.SYMBOL_PRICES ADD CONSTRAINT UN_SYMBOLPRICES_PRICEID UNIQUE (PRICEID);
ALTER TABLE PUBLIC.SYMBOL_PRICES ADD CONSTRAINT FK_SYMBOL_HISTORICALPRICE FOREIGN KEY(PRICEID) REFERENCES PUBLIC.HISTORICALPRICE(ID)

ALTER TABLE PUBLIC.SYMBOL ADD CONSTRAINT PK_SYMBOL_ID PRIMARY KEY (ID)
ALTER TABLE PUBLIC.SYMBOL ADD CONSTRAINT NN_SYMBOL_ID CHECK (ID IS NOT NULL);
ALTER TABLE PUBLIC.SYMBOL ADD CONSTRAINT NN_SYMBOL_ISCUSTOMPRICEFIRST CHECK (ISCUSTOMPRICEFIRST IS NOT NULL);
ALTER TABLE PUBLIC.SYMBOL ADD CONSTRAINT NN_SYMBOL_TICKER CHECK (TICKER IS NOT NULL);
ALTER TABLE PUBLIC.SYMBOL ADD CONSTRAINT NN_SYMBOL_CURRENCY CHECK (CURRENCY IS NOT NULL);
ALTER TABLE PUBLIC.SYMBOL ADD CONSTRAINT UN_SYMBOL_TICKER UNIQUE (TICKER);

ALTER TABLE PUBLIC.TRANSACTION_LABEL ADD CONSTRAINT PK_TRANSACTIONLABEL_IDS PRIMARY KEY (TRANSACTIONID, LABELID)
ALTER TABLE PUBLIC.TRANSACTION_LABEL ADD CONSTRAINT FK_TRANSACTION_LABEL FOREIGN KEY(LABELID) REFERENCES PUBLIC.LABEL(ID)
ALTER TABLE PUBLIC.TRANSACTION_LABEL ADD CONSTRAINT NN_TRANSACTIONLABEL_TRANSACTIONID CHECK (TRANSACTIONID IS NOT NULL);
ALTER TABLE PUBLIC.TRANSACTION_LABEL ADD CONSTRAINT NN_TRANSACTIONLABEL_LABELID CHECK (LABELID IS NOT NULL);

ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT PK_TRANSACTION_ID PRIMARY KEY (ID)
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT NN_TRANSACTION_ID CHECK (ID IS NOT NULL);
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT NN_TRANSACTION_COMMISSION CHECK (COMMISSION IS NOT NULL);
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT NN_TRANSACTION_PRICE CHECK (PRICE IS NOT NULL);
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT NN_TRANSACTION_QUANTITY CHECK (QUANTITY IS NOT NULL);
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT NN_TRANSACTION_DATE CHECK (DATE IS NOT NULL);
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT NN_TRANSACTION_TYPE CHECK (TYPE IS NOT NULL);
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT NN_TRANSACTION_SYMBOLID CHECK (SYMBOL_ID IS NOT NULL);
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT FK_TRANSACTION_SYMBOL FOREIGN KEY(SYMBOL_ID) REFERENCES PUBLIC.SYMBOL(ID)	

ALTER TABLE PUBLIC.VERSION ADD CONSTRAINT PK_VERSION_ID PRIMARY KEY (ID)
-- ALTER TABLE PUBLIC.VERSION ADD CONSTRAINT NN_VERSION_ID CHECK (ID IS NOT NULL);
--ALTER TABLE PUBLIC.VERSION ADD CONSTRAINT PK_VERSION_DATABASEVERSION PRIMARY KEY (DATABASEVERSION)
ALTER TABLE PUBLIC.VERSION ADD CONSTRAINT NN_VERSION_DATABASEVERSION CHECK (DATABASEVERSION IS NOT NULL);
ALTER TABLE PUBLIC.VERSION ADD CONSTRAINT CK_VERSION_DATABASEVERSION CHECK (DATABASEVERSION > 1);
ALTER TABLE PUBLIC.VERSION ADD CONSTRAINT UN_VERSION_DATABASEVERSION UNIQUE (DATABASEVERSION);
