ALTER TABLE PUBLIC.TRANSACTION ADD COLUMN TypeTmp VARCHAR(255);
ALTER TABLE PUBLIC.TRANSACTION DROP CONSTRAINT NN_TRANSACTION_TYPE;

UPDATE TRANSACTION SET TypeTmp='BUY' WHERE Type='0';
UPDATE TRANSACTION SET TypeTmp='SELL' WHERE Type='1';
UPDATE TRANSACTION SET TypeTmp='DIVIDEND' WHERE Type='2';

ALTER TABLE PUBLIC.TRANSACTION DROP COLUMN Type;
ALTER TABLE PUBLIC.TRANSACTION ALTER COLUMN TypeTmp RENAME TO Type;
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT NN_TRANSACTION_TYPE CHECK (Type IS NOT NULL);





