--------------------------------------------------------------------------------------------
SET DATABASE TRANSACTION CONTROL LOCKS
SET DATABASE DEFAULT ISOLATION LEVEL READ COMMITTED
SET FILES WRITE DELAY 500 MILLIS
SET FILES BACKUP INCREMENT TRUE
SET FILES CACHE SIZE 10000
SET FILES CACHE ROWS 50000
SET FILES SCALE 8
SET FILES LOB SCALE 32
SET FILES DEFRAG 20
SET FILES NIO TRUE
SET FILES NIO SIZE 256
SET FILES LOG TRUE
SET FILES LOG SIZE 50
SET DATABASE TEXT TABLE DEFAULTS ''
-- CREATE USER SA PASSWORD '';
-- CREATE SCHEMA PUBLIC AUTHORIZATION DBA;
SET SCHEMA PUBLIC

-- DROP SEQUENCE PUBLIC.HIBERNATE_SEQUENCE IF EXISTS
-- CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE AS INTEGER START WITH 0
----------------------------------------------------------------------------------------
ALTER SEQUENCE SYSTEM_LOBS.LOB_ID RESTART WITH 1
-- ALTER SEQUENCE PUBLIC.HIBERNATE_SEQUENCE RESTART WITH 60
SET DATABASE DEFAULT INITIAL SCHEMA PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.YES_OR_NO TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.TIME_STAMP TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CARDINAL_NUMBER TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CHARACTER_DATA TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.SQL_IDENTIFIER TO PUBLIC
-- GRANT DBA TO SA
SET SCHEMA SYSTEM_LOBS
-- INSERT INTO BLOCKS VALUES(0,2147483647,0)
SET SCHEMA PUBLIC




