ALTER TABLE PUBLIC.TRANSACTION ADD COLUMN transactionType VARCHAR(255);
ALTER TABLE PUBLIC.TRANSACTION DROP CONSTRAINT NN_TRANSACTION_TYPE;

UPDATE TRANSACTION SET transactionType='BUY' WHERE Type='0';
UPDATE TRANSACTION SET transactionType='SELL' WHERE Type='1';
UPDATE TRANSACTION SET transactionType='DIVIDEND' WHERE Type='2';

ALTER TABLE PUBLIC.TRANSACTION DROP COLUMN Type;
ALTER TABLE PUBLIC.TRANSACTION ALTER COLUMN TransactionType RENAME TO Type;
ALTER TABLE PUBLIC.TRANSACTION ADD CONSTRAINT NN_TRANSACTION_TYPE CHECK (Type IS NOT NULL);





